title: PIKUM STUDIOS
logo: C:\Users\Guillem\Documents\GitHub\Project-II-RPG\Output\Assets\Pikum_Logo.png
description: We are a small indie game company
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
